### ISSUE TITLE
Add a select, that lets the user filter month, or "all" based on bustable_date

### ISSUE THREAD

**Issue by JanBolmeson** [JanBolmeson/Buss#120]
http://www.trafikmatningar.se/rapporter/loneunderlag#

Make sure it works when exporting to excel as well.

![image](https://cloud.githubusercontent.com/assets/3698445/7144267/a4a0c484-e2e4-11e4-9aeb-1dcb41fc845b.png)

**Comment by bhaumikwork** [comment]
can you tell me which database is currently in use?
