### ISSUE TITLE
Mainmenu is opened when all timereports are shown

### ISSUE THREAD

**Issue by JanBolmeson** [JanBolmeson/Buss#31]
http://buss.bolmeson.se/rapporter/tidrapporter

![image](https://cloud.githubusercontent.com/assets/3698445/6340302/39066cee-bbbe-11e4-8f09-f6f196059560.png)

**Comment by bhaumikwork** [comment]
it doesn't be opened once page is loaded.. because menu is initialized using metismenu library which works on document ready!
