### ISSUE TITLE
Why do we have thre files? Isn't this possible to do in one (or two) files?

### ISSUE THREAD

**Issue by JanBolmeson** [JanBolmeson/Buss#36]
### Frequency Bus
  * https://github.com/JanBolmeson/Buss/blob/master/resources/views/reports/_form_report.blade.php
  * https://github.com/JanBolmeson/Buss/blob/master/resources/views/reports/_form_frequency_bus.blade.php

and 
  * https://github.com/JanBolmeson/Buss/blob/master/resources/views/frequency/reportBus.blade.php

**Comment by bhaumikwork** [comment]
they are good in seperation! the above 2 are for edit and in edit we don't consider old inputs.. and also it has very complex structure in edit as to consider saved values!!

**Comment by JanBolmeson** [comment]
ok, then!
