### ISSUE TITLE
Add summary-table to user profile

### ISSUE THREAD

**Issue by JanBolmeson** [JanBolmeson/Buss#41]
in:
http://buss.bolmeson.se/admin/users/1

Add summary of worked time via:
```sql
(
SELECT
    user_id,     
    is_type,
    SUM(count_normal_mins) AS count_total_normal_mins,
    SUM(count_ob1_mins) AS count_total_ob1_mins,
    SUM(count_ob2_mins) AS count_total_ob2_mins,
    SUM(count_ob3_mins) AS count_total_ob3_mins,
    SUM(count_total_mins) AS count_sum_all_mins 
FROM
    timereports 
WHERE deleted_at IS NULL 
    AND project_id = 1 AND user_id = 1
GROUP BY user_id , is_type
)
UNION
(
SELECT
    user_id,     
    "Sum",
    SUM(count_normal_mins) AS count_total_normal_mins,
    SUM(count_ob1_mins) AS count_total_ob1_mins,
    SUM(count_ob2_mins) AS count_total_ob2_mins,
    SUM(count_ob3_mins) AS count_total_ob3_mins,
    SUM(count_total_mins) AS count_sum_all_mins 
FROM
    timereports 
WHERE deleted_at IS NULL 
    AND project_id = 1 AND user_id = 1
GROUP BY user_id 
)
```
*Don't forget to change project_id and user_id

![image](https://cloud.githubusercontent.com/assets/3698445/6341320/832eafba-bbc9-11e4-8f4f-3c954cfbe08e.png)

**Comment by JanBolmeson** [comment]
This SQL
´´´sql
SELECT
    user_id,     
    is_type,
    SUM(count_normal_mins) AS count_total_normal_mins,
    SUM(count_ob1_mins) AS count_total_ob1_mins,
    SUM(count_ob2_mins) AS count_total_ob2_mins,
    SUM(count_ob3_mins) AS count_total_ob3_mins,
    SUM(count_total_mins) AS count_sum_all_mins 
FROM
    timereports 
WHERE deleted_at IS NULL 
    AND project_id = 1 AND user_id = 1
GROUP BY user_id , is_type; 
´´´

does show the following result:
![image](https://cloud.githubusercontent.com/assets/3698445/6358916/45761c8e-bc6f-11e4-9362-1865b4ede82e.png)

but your implementation in:
http://buss.bolmeson.se/admin/users/1

does only show total and not the table as in image above:

![image](https://cloud.githubusercontent.com/assets/3698445/6358926/5f5a5958-bc6f-11e4-92b9-cdda5362049e.png)

**Comment by JanBolmeson** [comment]
Can you change to this SQL so it gets the summary row as well:

```sql
(
SELECT
    user_id,     
    is_type,
    SUM(count_normal_mins) AS count_total_normal_mins,
    SUM(count_ob1_mins) AS count_total_ob1_mins,
    SUM(count_ob2_mins) AS count_total_ob2_mins,
    SUM(count_ob3_mins) AS count_total_ob3_mins,
    SUM(count_total_mins) AS count_sum_all_mins 
FROM
    timereports 
WHERE deleted_at IS NULL 
    AND project_id = 1 AND user_id = 1
GROUP BY user_id , is_type
)
UNION
(
SELECT
    user_id,     
    "Sum",
    SUM(count_normal_mins) AS count_total_normal_mins,
    SUM(count_ob1_mins) AS count_total_ob1_mins,
    SUM(count_ob2_mins) AS count_total_ob2_mins,
    SUM(count_ob3_mins) AS count_total_ob3_mins,
    SUM(count_total_mins) AS count_sum_all_mins 
FROM
    timereports 
WHERE deleted_at IS NULL 
    AND project_id = 1 AND user_id = 1
GROUP BY user_id 
)
```

**Comment by bhaumikwork** [comment]
i can directly calculate sum of all the columns no need to write such a complex query also we are using orm so it would be difficult to write such query still if you want me to use this query let me know i can use raw expressions in orm but total can be displayed without changing query let me know.
