### ISSUE TITLE
Report :: FrequencyBus and line (sv. tur) summary

### ISSUE THREAD

**Issue by JanBolmeson** [JanBolmeson/Buss#43]
in: http://buss.bolmeson.se/rapporter/linjestatistik-buss

Create table with the following info: 
  * busnumber "-" description (<-from frequency_buses)
  * number_of_done_rides  (<- calculate as count (number) of rows for that frequencey_bus_id in table "timereport_has_bus_frequency_count"
  * number_of_rides (<-  frequency_buses)
  * "Done in percentage" - the two previous cols number_of_done_rides/number_of_rides*100
  * Normal time (<- total count of "count_normal_mins" for that frequencey_bus_id)
  * ob1 (<- total_count of OB1 for that frequencey_bus_id)
  * ob2 (<- total_count of OB2 for that frequencey_bus_id)
  * ob3 (<- total_count of OB3 for that frequencey_bus_id)
  * total time (<- count_total_mins)

All normal|ob1|ob2... etc should be in "X tim YY min" via the Blade-extension or TimeCalculator::min2HandMin()

## Dump from old system
![image](https://cloud.githubusercontent.com/assets/3698445/6344942/f21651d6-bbff-11e4-9187-e5bb51cc7ad4.png)

**Comment by bhaumikwork** [comment]
can u explain the following
number_of_done_rides (<- calculate as count (number) of rows for that frequencey_bus_id in table "timereport_has_bus_frequency_count"
number_of_rides (<- frequency_buses)
"Done in percentage" - the two previous cols number_of_done_rides/number_of_rides*100
 i can't differentiate in them!

**Comment by bhaumikwork** [comment]
total_count means sum() of the report? because it gives very different value!
according to me it should like if bus_id 1 has 2 timereport for ex. with id 1 and 8 then total normal_mins = normal_mins for report id 1 + normal_mins for report id 8 and so on.. currently i have set the logic according to this let me know if any changes required!
