### ISSUE TITLE
Add page where you can add a person to a project

### ISSUE THREAD

**Issue by JanBolmeson** [JanBolmeson/Buss#50]
For now it shouldn't be able to delete a person from a project. 

table: ```user_belongs_to_projects```

**Comment by bhaumikwork** [comment]
can u describe which control should be used for adding person to project?
as there will be many projects and many users

**Comment by JanBolmeson** [comment]
On this page it can be a simple select, where you add one project at the time. Basically a select and an add-button. 

Then in #71 we add a more advanced column where we have many users for a project.

**Comment by bhaumikwork** [comment]
in select box it will have projects but that project will be for which user?

**Comment by JanBolmeson** [comment]
Sorry, this was meant in:
http://buss.bolmeson.se/admin/users/1/edit
